import {NextResponse} from 'next/server';import {randomUUID} from 'crypto';import {listAkta,saveAkta} from '@/lib/store';import {digits,num,str} from '@/lib/coerce';import {hasPihakData,pihakList,pihakNama,pihakNik,pihakNpwp} from '@/lib/akta';import type {Akta,Dokumen,PihakAkta,TandaTanganDigital} from '@/lib/types';
const cleanDokumen=(v:unknown):Dokumen[]=>Array.isArray(v)?v.filter((x:any)=>x&&x.url):[];
const cleanPihak=(v:unknown):PihakAkta[]=>Array.isArray(v)?v.slice(0,6).map((x:any)=>({nama:str(x?.nama).trim(),nik:digits(x?.nik,16),npwp:str(x?.npwp).trim(),scanIdentitas:cleanDokumen(x?.scanIdentitas)})).filter(hasPihakData):[];
const cleanTtd=(v:unknown):TandaTanganDigital[]=>Array.isArray(v)?v.filter((x:any)=>x&&x.dataUrl).map((x:any)=>({nama:str(x.nama),peran:str(x.peran),dataUrl:str(x.dataUrl),tanggal:str(x.tanggal)})):[];
function normalize(b:any,id?:string):Akta{const pihak=cleanPihak(b.pihak);const source=pihak.length?{pihak}:{namaPihak:str(b.namaPihak),nik:str(b.nik),npwp:str(b.npwp)};const fallback=pihakList(source).filter(hasPihakData);return {id:id||randomUUID(),nomorAkta:str(b.nomorAkta),tanggal:str(b.tanggal),kategori:b.kategori==='PPAT'?'PPAT':'NOTARIS',jenisAkta:str(b.jenisAkta),namaNotaris:str(b.namaNotaris),pihak:fallback,namaPihak:pihakNama({pihak:fallback},'; '),nik:pihakNik({pihak:fallback},'; '),npwp:pihakNpwp({pihak:fallback},'; '),alamat:str(b.alamat),nomorSertifikat:str(b.nomorSertifikat),jenisHak:str(b.jenisHak),luasTanah:str(b.luasTanah),nilaiTransaksi:num(b.nilaiTransaksi),nopPbb:str(b.nopPbb),njop:num(b.njop),tanggalSsp:str(b.tanggalSsp),sspPph:num(b.sspPph),tanggalBphtb:str(b.tanggalBphtb),bphtb:num(b.bphtb),honorarium:num(b.honorarium),status:b.status||'Draft',catatan:str(b.catatan),detail:typeof b.detail==='object'?b.detail:{},dokumen:cleanDokumen(b.dokumen),fotoTtdKlien:cleanDokumen(b.fotoTtdKlien),fotoTtdNotaris:cleanDokumen(b.fotoTtdNotaris),minuta:cleanDokumen(b.minuta),tandaTanganDigital:cleanTtd(b.tandaTanganDigital)}}
export async function GET(){return NextResponse.json(await listAkta())}
export async function POST(req:Request){const data=await listAkta();const a=normalize(await req.json());if(!a.pihak.length||!a.pihak[0].nama)return NextResponse.json({error:'Minimal nama pihak pertama wajib diisi'},{status:400});data.unshift(a);await saveAkta(data);return NextResponse.json({id:a.id},{status:201})}
export async function PUT(req:Request){const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'ID wajib'},{status:400});const data=await listAkta();const i=data.findIndex(x=>x.id===id);if(i<0)return NextResponse.json({error:'Data tidak ditemukan'},{status:404});const a=normalize(await req.json(),id);if(!a.pihak.length||!a.pihak[0].nama)return NextResponse.json({error:'Minimal nama pihak pertama wajib diisi'},{status:400});data[i]=a;await saveAkta(data);return NextResponse.json({id})}
export async function DELETE(req:Request){const id=new URL(req.url).searchParams.get('id');const data=await listAkta();await saveAkta(data.filter(x=>x.id!==id));return NextResponse.json({ok:true})}
